executable = mpi_sweep.sh
request_cpus = 1
request_memory = 16000
request_gpus = 1
request_disk = 200G
requirements = (TARGET.CUDACapability >= 7.0) && (TARGET.CUDAGlobalMemoryMb >=80000)
log_root = /home/preizinger/jobs/$(ClusterId)
error = $(log_root).err
output = $(log_root).out
log = $(log_root).log
MaxTime = 864000

periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

queue

